version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
    conda: "mambaforge"  # ✅ 强制启用 conda 构建（不能省略！）

conda:
  environment: environment_v2.yaml

sphinx:
  configuration: docs/source/conf.py

python:
  install: []  # ✅ 禁用默认 pip install，防止冲突
