channels:
- bioconda
- conda-forge
- defaults
dependencies:
- asttokens=2.0.5
- bzip2=1.0.8
- ca-certificates=2025.1.31
- comm=0.2.1
- debugpy=1.6.7
- decorator=5.1.1
- exceptiongroup=1.2.0
- executing=0.8.3
- ipykernel=6.29.5
- ipython=8.27.0
- jedi=0.19.1
- jupyter_client=8.6.0
- jupyter_core=5.7.2
- libffi=3.4.4
- libsodium=1.0.18
- libuuid=1.41.5
- matplotlib-inline=0.1.6
- ncurses=6.4
- nest-asyncio=1.6.0
- openssl=3.0.16
- packaging=24.1
- pandoc=3.6.4
- parso=0.8.3
- pexpect=4.8.0
- pip=24.2
- platformdirs=3.10.0
- prompt-toolkit=3.0.43
- prompt_toolkit=3.0.43
- psutil=5.9.0
- ptyprocess=0.7.0
- pure_eval=0.2.2
- pygments=2.15.1
- python=3.10.15
- python-dateutil=2.9.0post0
- pytz=2024.1
- pyyaml=6.0.2
- pyzmq=25.1.2
- readline=8.2
- setuptools=75.1.0
- six=1.16.0
- sqlite=3.45.3
- stack_data=0.2.0
- tk=8.6.14
- tornado=6.4.1
- traitlets=5.14.3
- typing_extensions=4.11.0
- tzdata=2025a
- wcwidth=0.2.5
- wheel=0.44.0
- xz=5.4.6
- yaml=0.2.5
- zeromq=4.3.5
- zlib=1.2.13
- intervaltree=3.1.0
- pip:
  - aiohappyeyeballs==2.4.3
  - aiohttp==3.11.6
  - aiosignal==1.3.1
  - alabaster==0.7.16
  - anndata==0.11.1
  - array-api-compat==1.9.1
  - async-timeout==5.0.1
  - attrs==24.2.0
  - babel==2.17.0
  - beautifulsoup4==4.13.4
  - bleach==6.2.0
  - certifi==2024.8.30
  - charset-normalizer==3.4.0
  - commonmark==0.9.1
  - contourpy==1.3.1
  - defusedxml==0.7.1
  - docutils==0.18.1
  - fastjsonschema==2.21.1
  - filelock==3.16.1
  - fonttools==4.55.0
  - frozenlist==1.5.0
  - fsspec==2024.10.0
  - idna==3.10
  - imagesize==1.4.1
  - jinja2==3.1.4
  - jsonschema==4.23.0
  - jsonschema-specifications==2024.10.1
  - jupyterlab-pygments==0.3.0
  - legacy-api-wrap==1.4
  - markdown-it-py==3.0.0
  - markupsafe==3.0.2
  - matplotlib==3.9.2
  - mdit-py-plugins==0.4.2
  - mdurl==0.1.2
  - mistune==3.1.3
  - mpmath==1.3.0
  - multidict==6.1.0
  - myst-parser==3.0.1
  - nbclient==0.10.2
  - nbconvert==7.16.6
  - nbformat==5.10.4
  - nbsphinx==0.9.7
  - networkx==3.4.2
  - numpy==1.26.4
  - opt-einsum==3.4.0
  - pandocfilters==1.5.1
  - patsy==1.0.1
  - pillow==11.0.0
  - propcache==0.2.0
  - pybedtools==0.10.0
  - pynndescent==0.5.13
  - pyparsing==3.2.0
  - pyro-api==0.1.2
  - pyro-ppl==1.9.1
  - pysam==0.23.0
  - recommonmark==0.7.1
  - referencing==0.36.2
  - requests==2.32.3
  - rpds-py==0.24.0
  - scanpy==1.10.4
  - scikit-learn==1.5.2
  - seaborn==0.13.2
  - snowballstemmer==2.2.0
  - soupsieve==2.6
  - sphinx==6.2.1
  - sphinx-autodoc-typehints==1.23.0
  - sphinx-copybutton==0.5.2
  - sphinx-rtd-theme==1.2.2
  - sphinxcontrib-applehelp==2.0.0
  - sphinxcontrib-devhelp==2.0.0
  - sphinxcontrib-htmlhelp==2.1.0
  - sphinxcontrib-jquery==4.1
  - sphinxcontrib-jsmath==1.0.1
  - sphinxcontrib-qthelp==2.0.0
  - sphinxcontrib-serializinghtml==2.0.0
  - stdlib-list==0.11.0
  - sympy==1.13.3
  - threadpoolctl==3.5.0
  - tinycss2==1.4.0
  - torch==2.2.2
  - torch-geometric==2.6.1
  - tqdm==4.67.0
  - umap-learn==0.5.7
  - urllib3==2.2.3
  - webencodings==0.5.1
  - yarl==1.17.2
name: DOLPHIN
