import argparse
import json
import sys


def build_parser():
    parser = argparse.ArgumentParser(
        description="Utilities for DOLPHIN preprocessing reference preparation and pipeline planning."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    prepare_reference = subparsers.add_parser(
        "prepare-reference",
        help="Generate the DOLPHIN exon reference bundle and optional STAR index.",
    )
    prepare_reference.add_argument(
        "--input-gtf",
        required=True,
        help="Path to the source Ensembl-style GTF file.",
    )
    prepare_reference.add_argument(
        "--output-dir",
        default=".",
        help="Parent directory that will receive the dolphin_exon_gtf folder.",
    )
    prepare_reference.add_argument(
        "--batch-size",
        type=int,
        default=10000,
        help="Number of genes to process per intermediate batch.",
    )
    prepare_reference.add_argument(
        "--genome-fasta",
        help="Optional genome FASTA path. If provided, STAR genomeGenerate will also run.",
    )
    prepare_reference.add_argument(
        "--star-binary",
        default="STAR",
        help="STAR executable name or absolute path.",
    )
    prepare_reference.add_argument(
        "--star-threads",
        type=int,
        default=16,
        help="Number of threads to use for STAR genomeGenerate.",
    )
    prepare_reference.add_argument(
        "--star-index-dir",
        help="Optional STAR index output directory. Defaults to <output-dir>/dolphin_exon_gtf/star_index.",
    )
    prepare_reference.add_argument(
        "--genome-sa-sparse-d",
        type=int,
        help="Optional STAR --genomeSAsparseD value.",
    )
    prepare_reference.add_argument(
        "--sjdb-overhang",
        type=int,
        help="Optional STAR --sjdbOverhang value.",
    )
    prepare_reference.add_argument(
        "--print-manifest",
        action="store_true",
        help="Print the generated reference manifest JSON to stdout.",
    )

    plan_preprocess = subparsers.add_parser(
        "plan-preprocess",
        help="Generate a runnable preprocessing plan for full-length or 10x data.",
    )
    plan_preprocess.add_argument(
        "--mode",
        required=True,
        choices=["full_length", "tenx"],
        help="Preprocessing mode to plan.",
    )
    plan_preprocess.add_argument(
        "--reference-manifest",
        required=True,
        help="Path to the reference_manifest.json generated by prepare-reference.",
    )
    plan_preprocess.add_argument(
        "--metadata-path",
        help="Optional metadata table containing at least a CB column. Not required when raw FASTQ discovery or STARsolo barcode outputs are sufficient.",
    )
    plan_preprocess.add_argument(
        "--raw-fastq-dir",
        required=True,
        help="Directory containing raw FASTQ files for the selected mode.",
    )
    plan_preprocess.add_argument(
        "--output-dir",
        required=True,
        help="Output directory that the generated preprocessing stages will target.",
    )
    plan_preprocess.add_argument(
        "--plan-dir",
        help="Directory where the preprocess plan JSON and shell script will be written. Defaults to --output-dir.",
    )
    plan_preprocess.add_argument(
        "--plan-script-name",
        default="run_preprocess.sh",
        help="Filename for the generated shell script.",
    )
    plan_preprocess.add_argument(
        "--plan-manifest-name",
        default="preprocess_plan.json",
        help="Filename for the generated preprocess plan manifest.",
    )
    plan_preprocess.add_argument(
        "--star-index-dir",
        help="Optional explicit STAR index directory. Otherwise resolve from the reference manifest.",
    )
    plan_preprocess.add_argument(
        "--star-binary",
        default="STAR",
        help="STAR executable name or absolute path.",
    )
    plan_preprocess.add_argument(
        "--featurecounts-binary",
        default="featureCounts",
        help="featureCounts executable name or absolute path.",
    )
    plan_preprocess.add_argument(
        "--star-threads",
        type=int,
        default=4,
        help="Number of threads to use for STAR or STARsolo.",
    )
    plan_preprocess.add_argument(
        "--featurecounts-threads",
        type=int,
        default=4,
        help="Number of threads to use for featureCounts.",
    )
    plan_preprocess.add_argument(
        "--print-plan",
        action="store_true",
        help="Print the generated preprocess plan JSON to stdout.",
    )
    plan_preprocess.add_argument(
        "--read-layout",
        choices=["single", "paired"],
        default="single",
        help="Full-length read layout. Used only when --mode full_length.",
    )
    plan_preprocess.add_argument(
        "--fastq-suffix",
        default=".fastq.gz",
        help="FASTQ suffix to expect for full-length inputs.",
    )
    plan_preprocess.add_argument(
        "--trim",
        action="store_true",
        help="Add Trimmomatic stages for full-length inputs.",
    )
    plan_preprocess.add_argument(
        "--java-binary",
        default="java",
        help="Java executable name or absolute path for Trimmomatic.",
    )
    plan_preprocess.add_argument(
        "--trimmomatic-jar",
        help="Required with --trim for full-length mode.",
    )
    plan_preprocess.add_argument(
        "--adapter-fasta",
        help="Required with --trim for full-length mode.",
    )
    plan_preprocess.add_argument(
        "--fail-on-missing-fastqs",
        action="store_true",
        help="Fail instead of skipping metadata rows whose FASTQ files are missing in full-length mode.",
    )
    plan_preprocess.add_argument(
        "--solo-whitelist",
        help="10x cell barcode whitelist file. Required when --mode tenx.",
    )
    plan_preprocess.add_argument(
        "--sample-name",
        help="Optional sample prefix to select a specific 10x FASTQ pair.",
    )
    plan_preprocess.add_argument(
        "--chemistry",
        default="10xv2",
        help="10x chemistry preset for STARsolo. Used only when --mode tenx.",
    )
    plan_preprocess.add_argument(
        "--solo-cell-filter",
        nargs="+",
        default=["CellRanger2.2", "3000", "0.99", "10"],
        help="STARsolo cell filtering arguments. Use 'None' to disable STARsolo cell calling in tenx mode.",
    )
    plan_preprocess.add_argument(
        "--samtools-binary",
        default="samtools",
        help="samtools executable name or absolute path. Used only when --mode tenx.",
    )
    plan_preprocess.add_argument(
        "--barcode-tag",
        default="CB",
        help="Barcode tag to copy from the STARsolo BAM in tenx mode.",
    )
    plan_preprocess.add_argument(
        "--rg-tag",
        default="RG",
        help="Read group tag to write for grouped featureCounts in tenx mode.",
    )
    plan_preprocess.add_argument(
        "--append-suffix",
        help="Optional suffix appended to barcode values before writing RG tags in tenx mode.",
    )
    plan_preprocess.add_argument(
        "--metadata-cb-suffix",
        help="Optional 10x metadata CB suffix filter, for example _Colon-1. Used only when --mode tenx.",
    )

    run_preprocess = subparsers.add_parser(
        "run-preprocess",
        help="Execute a preprocess plan and record per-stage logs and timing.",
    )
    run_preprocess.add_argument(
        "--plan-manifest",
        required=True,
        help="Path to a preprocess_plan.json generated by plan-preprocess.",
    )
    run_preprocess.add_argument(
        "--log-dir",
        help="Optional override for the execution log directory. Defaults to the plan logs directory.",
    )
    run_preprocess.add_argument(
        "--timing-path",
        help="Optional override for the tab-delimited execution timing file.",
    )
    run_preprocess.add_argument(
        "--summary-path",
        help="Optional override for the execution summary JSON file.",
    )
    run_preprocess.add_argument(
        "--resume",
        action="store_true",
        help="Skip stages whose declared outputs already exist.",
    )
    run_preprocess.add_argument(
        "--continue-on-error",
        action="store_true",
        help="Continue executing later stages even if a stage fails.",
    )
    run_preprocess.add_argument(
        "--max-parallel-cells",
        type=int,
        help="Optional full-length cell concurrency. Use a positive integer to run multiple cells in parallel.",
    )
    run_preprocess.add_argument(
        "--parallel-profile",
        choices=["conservative", "balanced", "aggressive"],
        help="Optional full-length concurrency profile from the plan's recommended parallelism block.",
    )
    run_preprocess.add_argument(
        "--print-summary",
        action="store_true",
        help="Print the execution summary JSON to stdout.",
    )

    recommend_parallelism = subparsers.add_parser(
        "recommend-parallelism",
        help="Inspect current system resources and suggest full-length cell parallelism profiles.",
    )
    recommend_parallelism.add_argument(
        "--sample-count",
        type=int,
        required=True,
        help="Number of full-length cells that may be scheduled.",
    )
    recommend_parallelism.add_argument(
        "--star-threads",
        type=int,
        default=4,
        help="STAR threads per full-length cell.",
    )
    recommend_parallelism.add_argument(
        "--featurecounts-threads",
        type=int,
        default=4,
        help="featureCounts threads per full-length cell.",
    )

    split_featurecounts = subparsers.add_parser(
        "split-featurecounts",
        help="Split grouped featureCounts output into one DOLPHIN-compatible file per cell.",
    )
    split_featurecounts.add_argument(
        "--mode",
        required=True,
        choices=["gene", "exon", "junction"],
        help="Grouped featureCounts file type to split.",
    )
    split_featurecounts.add_argument(
        "--input-path",
        required=True,
        help="Path to the grouped featureCounts output file.",
    )
    split_featurecounts.add_argument(
        "--output-dir",
        required=True,
        help="Directory that will receive the per-cell output files.",
    )
    split_featurecounts.add_argument(
        "--metadata-path",
        help="Optional metadata table used to restrict and order output cells.",
    )
    split_featurecounts.add_argument(
        "--cell-id-list-path",
        help="Optional newline-delimited cell or barcode list used to restrict and order output cells.",
    )
    split_featurecounts.add_argument(
        "--summary-path",
        help="Optional JSON path that will receive a split summary. Useful as a stage completion sentinel.",
    )
    split_featurecounts.add_argument(
        "--print-summary",
        action="store_true",
        help="Print a JSON summary of written and missing cells.",
    )

    combine_featurecounts = subparsers.add_parser(
        "combine-featurecounts",
        help="Combine one-file-per-cell featureCounts outputs into a grouped matrix.",
    )
    combine_featurecounts.add_argument(
        "--mode",
        required=True,
        choices=["gene", "exon", "junction"],
        help="Legacy featureCounts file type to combine.",
    )
    combine_featurecounts.add_argument(
        "--input-dir",
        required=True,
        help="Directory containing one featureCounts file per cell.",
    )
    combine_featurecounts.add_argument(
        "--output-path",
        required=True,
        help="Path for the grouped featureCounts-style output file.",
    )
    combine_featurecounts.add_argument(
        "--cell-id-list-path",
        help="Optional newline-delimited cell list used to define grouped column order.",
    )
    combine_featurecounts.add_argument(
        "--summary-path",
        help="Optional JSON path that will receive a combination summary.",
    )
    combine_featurecounts.add_argument(
        "--print-summary",
        action="store_true",
        help="Print a JSON summary of the grouped output.",
    )

    merge_grouped_featurecounts = subparsers.add_parser(
        "merge-grouped-featurecounts",
        help="Merge grouped featureCounts matrices across multiple samples.",
    )
    merge_grouped_featurecounts.add_argument(
        "--mode",
        required=True,
        choices=["gene", "exon", "junction"],
        help="Grouped featureCounts file type to merge.",
    )
    merge_grouped_featurecounts.add_argument(
        "--input-path",
        action="append",
        required=True,
        help="Grouped featureCounts input file. Use once per sample.",
    )
    merge_grouped_featurecounts.add_argument(
        "--output-path",
        required=True,
        help="Path for the merged grouped featureCounts output file.",
    )
    merge_grouped_featurecounts.add_argument(
        "--sample-label",
        action="append",
        help="Optional sample label paired with each --input-path. Recommended for multi-sample 10x merges so cell IDs become sample__barcode.",
    )
    merge_grouped_featurecounts.add_argument(
        "--cell-id-list-output-path",
        help="Optional newline-delimited merged cell ID list output.",
    )
    merge_grouped_featurecounts.add_argument(
        "--cell-manifest-output-path",
        help="Optional merged cell manifest TSV output with a CB column.",
    )
    merge_grouped_featurecounts.add_argument(
        "--summary-path",
        help="Optional JSON path that will receive a grouped merge summary.",
    )
    merge_grouped_featurecounts.add_argument(
        "--print-summary",
        action="store_true",
        help="Print a JSON summary of the merged grouped output.",
    )

    validate_grouped_featurecounts = subparsers.add_parser(
        "validate-grouped-featurecounts",
        help="Validate that a grouped featureCounts file contains grouped count columns.",
    )
    validate_grouped_featurecounts.add_argument(
        "--mode",
        required=True,
        choices=["gene", "exon", "junction"],
        help="Grouped featureCounts file type to validate.",
    )
    validate_grouped_featurecounts.add_argument(
        "--input-path",
        required=True,
        help="Path to the grouped featureCounts output file.",
    )
    validate_grouped_featurecounts.add_argument(
        "--print-summary",
        action="store_true",
        help="Print a JSON summary of the validated grouped file.",
    )

    cb_to_rg = subparsers.add_parser(
        "cb-to-rg",
        help="Copy a barcode tag from SAM input into an RG tag on stdout.",
    )
    cb_to_rg.add_argument(
        "--barcode-tag",
        default="CB",
        help="Barcode tag to read from each SAM alignment record.",
    )
    cb_to_rg.add_argument(
        "--rg-tag",
        default="RG",
        help="Read group tag to write to each SAM alignment record.",
    )
    cb_to_rg.add_argument(
        "--append-suffix",
        help="Optional suffix appended to the barcode value before writing RG.",
    )
    cb_to_rg.add_argument(
        "--input-bam",
        help="Optional BAM input path for BAM-native rewriting via pysam.",
    )
    cb_to_rg.add_argument(
        "--output-bam",
        help="Optional BAM output path for BAM-native rewriting via pysam.",
    )
    cb_to_rg.add_argument(
        "--allow-list-path",
        help="Optional newline-delimited barcode list. Alignments whose barcode tag is not in this list will be dropped.",
    )
    cb_to_rg.add_argument(
        "--threads",
        type=int,
        default=1,
        help="Optional BAM I/O thread count for BAM-native cb-to-rg rewriting.",
    )
    cb_to_rg.add_argument(
        "--write-index",
        action="store_true",
        help="Write a BAM index after BAM-native cb-to-rg rewriting completes.",
    )
    cb_to_rg.add_argument(
        "--stats-path",
        help="Optional JSON file that will receive summary statistics for the streamed conversion.",
    )

    return parser


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.command == "prepare-reference":
        from .generate_exon_gtf import prepare_reference_bundle

        manifest = prepare_reference_bundle(
            input_gtf_path=args.input_gtf,
            output_dir=args.output_dir,
            batch_size=args.batch_size,
            genome_fasta_path=args.genome_fasta,
            star_executable=args.star_binary,
            star_threads=args.star_threads,
            star_index_dir=args.star_index_dir,
            genome_sa_sparse_d=args.genome_sa_sparse_d,
            sjdb_overhang=args.sjdb_overhang,
        )
        if args.print_manifest:
            print(json.dumps(manifest, indent=2, sort_keys=True))
        return 0

    if args.command == "plan-preprocess":
        from .pipeline import (
            build_full_length_preprocess_plan,
            build_tenx_preprocess_plan,
            write_preprocess_plan,
        )

        if args.mode == "full_length":
            plan = build_full_length_preprocess_plan(
                reference_manifest_path=args.reference_manifest,
                metadata_path=args.metadata_path,
                raw_fastq_dir=args.raw_fastq_dir,
                output_dir=args.output_dir,
                read_layout=args.read_layout,
                fastq_suffix=args.fastq_suffix,
                star_binary=args.star_binary,
                featurecounts_binary=args.featurecounts_binary,
                star_threads=args.star_threads,
                featurecounts_threads=args.featurecounts_threads,
                trim=args.trim,
                java_binary=args.java_binary,
                trimmomatic_jar=args.trimmomatic_jar,
                adapter_fasta=args.adapter_fasta,
                skip_missing_fastqs=not args.fail_on_missing_fastqs,
                explicit_star_index_dir=args.star_index_dir,
            )
        else:
            if not args.solo_whitelist:
                parser.error("--solo-whitelist is required when --mode tenx")
            plan = build_tenx_preprocess_plan(
                reference_manifest_path=args.reference_manifest,
                metadata_path=args.metadata_path,
                raw_fastq_dir=args.raw_fastq_dir,
                output_dir=args.output_dir,
                solo_whitelist_path=args.solo_whitelist,
                sample_name=args.sample_name,
                chemistry=args.chemistry,
                star_binary=args.star_binary,
                featurecounts_binary=args.featurecounts_binary,
                samtools_binary=args.samtools_binary,
                star_threads=args.star_threads,
                featurecounts_threads=args.featurecounts_threads,
                solo_cell_filter_args=args.solo_cell_filter,
                barcode_tag=args.barcode_tag,
                rg_tag=args.rg_tag,
                append_suffix=args.append_suffix,
                metadata_cb_suffix=args.metadata_cb_suffix,
                explicit_star_index_dir=args.star_index_dir,
            )

        plan_dir = args.plan_dir or args.output_dir
        plan_outputs = write_preprocess_plan(
            plan=plan,
            output_dir=plan_dir,
            script_name=args.plan_script_name,
            manifest_name=args.plan_manifest_name,
        )

        result = {
            "plan_manifest_path": plan_outputs["manifest_path"],
            "plan_script_path": plan_outputs["script_path"],
            "mode": plan["mode"],
            "stage_count": len(plan["stages"]),
            "warnings": plan.get("warnings", []),
        }
        if args.print_plan:
            result["plan"] = plan
        print(json.dumps(result, indent=2, sort_keys=True))
        return 0

    if args.command == "run-preprocess":
        from .pipeline import run_preprocess_plan

        summary = run_preprocess_plan(
            plan_manifest_path=args.plan_manifest,
            log_dir=args.log_dir,
            timing_path=args.timing_path,
            summary_path=args.summary_path,
            resume=args.resume,
            continue_on_error=args.continue_on_error,
            max_parallel_cells=args.max_parallel_cells,
            parallel_profile=args.parallel_profile,
        )
        if args.print_summary:
            print(json.dumps(summary, indent=2, sort_keys=True))
        return 0

    if args.command == "recommend-parallelism":
        from .pipeline import recommend_full_length_parallelism

        recommendation = recommend_full_length_parallelism(
            sample_count=args.sample_count,
            star_threads=args.star_threads,
            featurecounts_threads=args.featurecounts_threads,
        )
        print(json.dumps(recommendation, indent=2, sort_keys=True))
        return 0

    if args.command == "split-featurecounts":
        from .pipeline import split_grouped_featurecounts

        summary = split_grouped_featurecounts(
            input_path=args.input_path,
            output_dir=args.output_dir,
            mode=args.mode,
            metadata_path=args.metadata_path,
            cell_id_list_path=args.cell_id_list_path,
            summary_path=args.summary_path,
        )
        if args.print_summary:
            print(json.dumps(summary, indent=2, sort_keys=True))
        return 0

    if args.command == "combine-featurecounts":
        from .pipeline import combine_featurecounts_directory

        summary = combine_featurecounts_directory(
            input_dir=args.input_dir,
            output_path=args.output_path,
            mode=args.mode,
            cell_id_list_path=args.cell_id_list_path,
            summary_path=args.summary_path,
        )
        if args.print_summary:
            print(json.dumps(summary, indent=2, sort_keys=True))
        return 0

    if args.command == "merge-grouped-featurecounts":
        from .pipeline import merge_grouped_featurecounts_files

        summary = merge_grouped_featurecounts_files(
            input_paths=args.input_path,
            output_path=args.output_path,
            mode=args.mode,
            sample_labels=args.sample_label,
            summary_path=args.summary_path,
            cell_id_list_output_path=args.cell_id_list_output_path,
            cell_manifest_output_path=args.cell_manifest_output_path,
        )
        if args.print_summary:
            print(json.dumps(summary, indent=2, sort_keys=True))
        return 0

    if args.command == "validate-grouped-featurecounts":
        from .pipeline import validate_grouped_featurecounts

        summary = validate_grouped_featurecounts(
            input_path=args.input_path,
            mode=args.mode,
        )
        if args.print_summary:
            print(json.dumps(summary, indent=2, sort_keys=True))
        return 0

    if args.command == "cb-to-rg":
        from .pipeline import rewrite_bam_cb_to_rg, stream_cb_to_rg

        if bool(args.input_bam) != bool(args.output_bam):
            parser.error("--input-bam and --output-bam must be provided together")

        if args.input_bam:
            summary = rewrite_bam_cb_to_rg(
                input_bam_path=args.input_bam,
                output_bam_path=args.output_bam,
                barcode_tag=args.barcode_tag,
                rg_tag=args.rg_tag,
                append_suffix=args.append_suffix,
                allow_list_path=args.allow_list_path,
                threads=args.threads,
                write_index=args.write_index,
            )
        else:
            summary = stream_cb_to_rg(
                input_stream=sys.stdin,
                output_stream=sys.stdout,
                barcode_tag=args.barcode_tag,
                rg_tag=args.rg_tag,
                append_suffix=args.append_suffix,
                allow_list_path=args.allow_list_path,
            )
        if args.stats_path:
            with open(args.stats_path, "w", encoding="utf-8") as handle:
                json.dump(summary, handle, indent=2, sort_keys=True)
                handle.write("\n")
        return 0

    parser.error(f"Unknown command: {args.command}")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
